#include "../../inc/Projects/ProjectTwo.hpp"
#include <iostream>

/**
 * @author Zachary Waldron
 * @date 2025-05-12
 * @brief Project Two Even Fibonacci Numbers
 * @details This project calculates the sum of even Fibonacci numbers up to a given limit.
 * @note This project is a simple implementation of the Fibonacci sequence and demonstrates
 *       the use of loops and conditionals in C++.
 * @warning This project is for educational purposes only and should not be used in production.
 * @license Apache-2.0 All rights reserved.
 * @see
 * 
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
 * By starting with and , the first terms will be: 
 * 1,2,3,5,8,13,21,34,55,89,...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
 * find the sum of the even-valued terms.
 * 
 */

int Projects::ProjectTwo::run() {
    std::cout << "" << std::endl;

    unsigned short ID = this->getID();
    std::cout << "Project ID: " << ID << std::endl;

    return 0;
}

unsigned short Projects::ProjectTwo::getID() {
    return this->PID;
}

Projects::ProjectTwo::~ProjectTwo() {
    std::cout << "Destructor Reached" << std::endl;
}
